upstream backend_nodes {
    server airquality-backend:5000;
}

upstream frontend_nodes {
    server airquality-frontend:5173;
}

server {
    listen 9910;
    server_name _;

    # Public API
    location /api/public/ {
        proxy_pass http://backend_nodes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Header for CORS, allowing access to the confidential API only from the frontend, 
        # but without forwarding the real client IP to the backend.
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
    }

    # This is the best practice to prevent IP Spoofing and ensure the backend knows the real client IP.
    # It forwards the original client's IP address to the backend server.
    # Route only accessible via VPN.
    location /api/confidential/ {
        # VPN ip range.
        allow 10.6.0.0/24;
        # for testing, allow localhost.
        allow 127.0.0.1;
        # deny all other IPs.
        deny all;

        proxy_pass http://backend_nodes;
        
        # For best practices, forward the original client's IP and host information to the backend.
        # This prevent IP Spoofing and allows the backend to know the real client IP.
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;

        # Header for CORS, allowing access to the confidential API only from the frontend, 
        # but without forwarding the real client IP to the backend.
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
    }

    # Refering to the frontend, we want to allow access to everyone, but we don't want to forward
    # the real client IP to the backend, because it could be used for IP Spoofing attacks.
    location / {
        proxy_pass http://frontend_nodes;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}